on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Install dependencies
      run: dotnet restore ./BotFrameworkTwitterAdapter/BotFrameworkTwitterAdapter.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ./BotFrameworkTwitterAdapter/BotFrameworkTwitterAdapter.csproj
#     - name: Test
#       run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release ./BotFrameworkTwitterAdapter/BotFrameworkTwitterAdapter.csproj

    # https://docs.github.com/ja/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages
    - name: Add NuGet Package Source
      run: dotnet nuget add source https://nuget.pkg.github.com/7474/index.json -n github -u 7474 -p "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text
    - name: Push NuGet Package
      run: dotnet nuget push "./BotFrameworkTwitterAdapter/bin/Release/BotFrameworkTwitterAdapter.*.nupkg" --source "github"
